name: RDP via Serveo

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create RDP user & enable RDP
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" `
            -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Open Serveo Tunnel for RDP
        shell: powershell
        run: |
          # -T disables pseudo-terminal allocation
          # -N tells SSH not to run any remote commands (just port forwarding)
          ssh -T -N -o StrictHostKeyChecking=no -R 0:localhost:3389 serveo.net
          
