name: RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable RDP Access
      run: |
        net user runneradmin MyStrongPasswords123 /add
        net localgroup administrators runneradmins /add
        Enable-ComputerRestore -Drive "C:\"
        vssadmin resize shadowstorage /for=C: /on=C: /MaxSize=10%
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Keep Alive for 6 Hours
      run: |
        for /l %%x in (1, 1, 360) do (
          echo Running %%x...
          timeout /t 60
        )
