name: RDP via Serveo

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Create RDP user & enable RDP
        run: |
          net user kamel123 MyStrong123 /add
          net localgroup administrators kamel123 /add
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Open Serveo Tunnel for RDP
        shell: powershell
        run: |
          # This asks Serveo for a public port and forwards it to your 3389
          $out = ssh -o StrictHostKeyChecking=no -R 0:0.0.0.0:3389:localhost:3389 serveo.net 2>&1
          Write-Host $out
          Start-Sleep -Seconds 21600   # keep tunnel alive up to 6 hrs
